<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pro" name="unitbv.tests.CheckUnitBV" tests="9" failures="0" timestamp="15 Jun 2019 08:22:34 GMT" time="15.011" errors="1">
  <testcase name="verifyUrlUsingXPath" time="0.932" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="1.098" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="1.173" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="6.100" classname="unitbv.tests.CheckUnitBV">
    <error type="java.lang.AssertionError" message="15-06_11-22-09 [ERROR] - Element //span[contains(.,&#039;Raporarte&#039;)] not found on page">
      <![CDATA[java.lang.AssertionError: 15-06_11-22-09 [ERROR] - Element //span[contains(.,'Raporarte')] not found on page
	at org.testng.Assert.fail(Assert.java:94)
	at framework.TestOperations.assertElementPresent(Unknown Source)
	at util.VerifyPagesFromXls.verifyUrlUsingXPath(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- verifyUrlUsingXPath -->
  <testcase name="verifyUrlUsingXPath" time="1.778" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="1.180" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="0.816" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="1.049" classname="unitbv.tests.CheckUnitBV"/>
  <testcase name="verifyUrlUsingXPath" time="0.885" classname="unitbv.tests.CheckUnitBV"/>
</testsuite> <!-- unitbv.tests.CheckUnitBV -->
